#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application();

$app->register('sayHelloTo')
    ->addArgument('name')
    ->setCode(function (InputInterface $input, OutputInterface $output)
    {
        $output->writeIn('Hello World');
    });

$app->run();

